# Generated by Django 2.2.7 on 2019-11-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=4)),
                ('attempts', models.IntegerField(default=3)),
                ('ban_date', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
