# Generated by Django 2.2.7 on 2019-12-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191222_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userpic',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='userpics'),
        ),
    ]
