# Generated by Django 2.2.7 on 2020-01-22 12:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
