# Generated by Django 3.0.3 on 2020-02-25 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iban',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
    ]
