# Generated by Django 2.2.7 on 2020-01-17 14:21

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200113_0013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageModel',
            new_name='Message',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=core.models.nameFile)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.Message')),
            ],
        ),
    ]
