# Generated by Django 3.0.3 on 2020-03-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0009_auto_20200314_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['-name'], 'verbose_name': 'Область', 'verbose_name_plural': 'Области'},
        ),
    ]
