# Generated by Django 2.2.7 on 2019-11-21 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20191121_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation_house',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_accom', to='house.House'),
        ),
    ]
