# Generated by Django 2.2.7 on 2019-12-09 12:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20191209_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NearBuildingHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housenearbuildings', to='house.House')),
                ('nearbuilding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearbuildings', to='house.NearBuilding')),
            ],
        ),
    ]
