# Generated by Django 2.2.7 on 2019-11-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20191121_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accommodation_house',
            new_name='AccommodationHouse',
        ),
        migrations.RenameModel(
            old_name='House_room',
            new_name='HouseRoom',
        ),
    ]
