# Generated by Django 2.2.7 on 2019-11-30 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20191121_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationhouse',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houseaccoms', to='house.House'),
        ),
    ]
