# Generated by Django 2.2.7 on 2019-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20191209_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='stars',
        ),
        migrations.AddField(
            model_name='house',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
