# Generated by Django 2.2.7 on 2019-12-04 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0005_auto_20191130_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='fri',
        ),
        migrations.RemoveField(
            model_name='house',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='house',
            name='sat',
        ),
        migrations.RemoveField(
            model_name='house',
            name='sun',
        ),
        migrations.RemoveField(
            model_name='house',
            name='thu',
        ),
        migrations.RemoveField(
            model_name='house',
            name='tue',
        ),
        migrations.RemoveField(
            model_name='house',
            name='wed',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='house.House')),
            ],
        ),
    ]
