# Generated by Django 2.2.7 on 2019-12-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20191211_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
