# Generated by Django 2.2.7 on 2019-12-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_auto_20191212_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housetype',
            name='description',
        ),
    ]
