# Generated by Django 2.2.7 on 2019-12-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_remove_housetype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='rules',
            field=models.ManyToManyField(to='house.Rule'),
        ),
        migrations.DeleteModel(
            name='RuleHouse',
        ),
    ]
