# Generated by Django 2.2.7 on 2019-12-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_auto_20191218_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freedateinterval',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_dates', to='house.House'),
        ),
    ]
