# Generated by Django 2.2.7 on 2019-12-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0014_auto_20191221_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
