# Generated by Django 2.2.7 on 2020-01-21 13:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('house', '0014_auto_20191221_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDateInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='freedateinterval',
            name='house',
        ),
        migrations.AddField(
            model_name='house',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='discount30days',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='house',
            name='discount7days',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='house',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='beds',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
        migrations.AlterField(
            model_name='house',
            name='guests',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.HouseType'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='rooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='house',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='house.House'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='FreeDateInterval',
        ),
        migrations.AddField(
            model_name='blockeddateinterval',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='house.House'),
        ),
    ]
