# Generated by Django 2.2.7 on 2020-01-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0015_auto_20200121_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
