# Generated by Django 2.2.7 on 2019-12-30 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0015_auto_20191229_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='house.House'),
        ),
    ]
