# Generated by Django 2.2.7 on 2020-01-29 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0016_auto_20200125_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
