# Generated by Django 2.2.7 on 2019-12-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0016_auto_20191222_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDateInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='')),
                ('date_end', models.DateField(verbose_name='')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='house.House')),
            ],
        ),
        migrations.DeleteModel(
            name='FreeDateInterval',
        ),
    ]
