# Generated by Django 2.2.7 on 2020-01-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0016_auto_20191230_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
