# Generated by Django 2.2.7 on 2019-12-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0017_auto_20191222_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='beds',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='guests',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='rooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
