# Generated by Django 2.2.7 on 2020-01-06 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0017_house_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='discount30days',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='house',
            name='discount7days',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
