# Generated by Django 3.0.3 on 2020-03-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0018_auto_20200208_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='beds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
