# Generated by Django 2.2.7 on 2020-01-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0018_auto_20200107_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
