# Generated by Django 3.0.3 on 2020-03-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0019_auto_20200311_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
