# Generated by Django 3.0.3 on 2020-03-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0021_auto_20200314_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodation',
            options={'verbose_name': 'Удобство', 'verbose_name_plural': 'Удобства'},
        ),
        migrations.AlterModelOptions(
            name='blockeddateinterval',
            options={'verbose_name': 'Несвободная дата', 'verbose_name_plural': 'Несвободные даты'},
        ),
        migrations.AlterModelOptions(
            name='favourite',
            options={'verbose_name': 'Избранный', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AlterModelOptions(
            name='housetype',
            options={'verbose_name': 'Вид жилья', 'verbose_name_plural': 'Виды жилья'},
        ),
        migrations.AlterModelOptions(
            name='nearbuilding',
            options={'verbose_name': 'Ближайшая организация', 'verbose_name_plural': 'Ближайшие организации'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии объявлений'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'Правило', 'verbose_name_plural': 'Правила'},
        ),
    ]
