# Generated by Django 2.2.7 on 2019-12-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20191221_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='accepted_house',
            field=models.BooleanField(default=False),
        ),
    ]
