# Generated by Django 2.2.7 on 2020-01-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20191229_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='accepted_house',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Canceled')], default=0),
        ),
    ]
