# Generated by Django 2.2.7 on 2020-01-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20200109_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='message',
            field=models.CharField(default='everything was ok', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
