# Generated by Django 2.2.7 on 2020-01-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20200125_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Canceled'), (2, 'Expired')], default=0),
        ),
    ]
