# Generated by Django 2.2.7 on 2020-01-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20200128_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
