# Generated by Django 3.0.3 on 2020-02-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_reservation_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
