# Generated by Django 3.0.3 on 2020-03-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_auto_20200304_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='accepted_house',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_paid',
        ),
    ]
