# Generated by Django 3.0.3 on 2020-03-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_auto_20200304_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Request'), (1, 'Approved'), (2, 'Rejected'), (3, 'Paid'), (4, 'Canceled'), (5, 'Expired')], default=0),
        ),
    ]
