# Generated by Django 3.0.3 on 2020-03-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_auto_20200305_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
    ]
