# Generated by Django 2.2.7 on 2020-02-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200205_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
